import { Footer } from "./components/footer"
import { Header } from "./components/header"
import { aboutMeData, pages } from '../app/components/data/data'
import "./components/global.css";

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header name={aboutMeData.name} pages={pages} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
